const ENUM_USER_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  USER: "USER",
};

const ENUM_AUCTION_STATUS = {
  UPCOMING: "UPCOMING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
};

module.exports = {
  ENUM_USER_ROLE,
  ENUM_AUCTION_STATUS,
};
