const ENUM_USER_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  USER: "USER",
};

const ENUM_AUCTION_STATUS = {
  UPCOMING: "UPCOMING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
};

const ENUM_PAID_BY = {
  CREDIT_CARD: "CREDIT_CARD",
  PAYPAL: "PAYPAL",
  OTHER: "OTHER",
};

const ENUM_DELIVERY_STATUS = {
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
};

const ENUM_PAYMENT_STATUS = {
  PAID: "PAID",
  UNPAID: "UNPAID",
};

const ENUM_ITEM_TYPE = {
  PRODUCT: "PRODUCT",
  BID: "BID",
};
const ENUM_AUTH_TYPE = {
  GOOGLE: "GOOGLE",
  MANUAL: "MANUAL",
};

const ENUM_PAYMENT_TYPE = {
  FULL_PAYMENT: "FULL_PAYMENT",
  INSTALLMENT: "INSTALLMENT",
};

const ENUM_ORDER_TYPE = {
  NORMAL: "NORMAL",
  FINANCE: "FINANCE",
};

module.exports = {
  ENUM_USER_ROLE,
  ENUM_AUCTION_STATUS,
  ENUM_PAID_BY,
  ENUM_DELIVERY_STATUS,
  ENUM_PAYMENT_STATUS,
  ENUM_ITEM_TYPE,
  ENUM_AUTH_TYPE,
  ENUM_PAYMENT_TYPE,
  ENUM_ORDER_TYPE,
};
